/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomTheme {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'prompt' : string,
}
export interface DesignEntry {
  'principal' : Principal,
  'createdAt' : Time,
  'style' : string,
  'roomType' : string,
}
export interface PlanLimits {
  'plan' : SubscriptionPlan,
  'videoLimit' : bigint,
  'price' : bigint,
  'photoLimit' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionPlan = { 'max' : null } |
  { 'pro' : null } |
  { 'growth' : null } |
  { 'starter' : null } |
  { 'basic' : null };
export interface SubscriptionUsage {
  'lastReset' : Time,
  'photosUsed' : bigint,
  'createdAt' : Time,
  'plan' : SubscriptionPlan,
  'videosUsed' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomTheme' : ActorMethod<[string, string], bigint>,
  'addDesign' : ActorMethod<[string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimRazorpayPayment' : ActorMethod<[string, SubscriptionPlan], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCustomTheme' : ActorMethod<[bigint], undefined>,
  'getAllDesigns' : ActorMethod<[], Array<DesignEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesignHistorySorted' : ActorMethod<[], Array<DesignEntry>>,
  'getMyCustomThemes' : ActorMethod<[], Array<CustomTheme>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  'getMySubscription' : ActorMethod<[], SubscriptionUsage>,
  'getPlanLimitsQuery' : ActorMethod<[SubscriptionPlan], PlanLimits>,
  'getPuterToken' : ActorMethod<[], string>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'recordPhotoUsage' : ActorMethod<[], undefined>,
  'recordVideoUsage' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegister' : ActorMethod<[string], undefined>,
  'setPuterToken' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserPlan' : ActorMethod<[Principal, SubscriptionPlan], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMyProfile' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];