/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AiGenerationLog {
  'id' : bigint,
  'createdAt' : Time,
  'inputImageBlobId' : string,
  'userPrincipal' : Principal,
  'prompt' : string,
  'outputImageBlobId' : string,
}
export interface CustomTheme {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'prompt' : string,
}
export interface DesignEntry {
  'principal' : Principal,
  'createdAt' : Time,
  'style' : string,
  'roomType' : string,
}
export type ExternalBlob = Uint8Array;
export interface PlanLimits {
  'plan' : SubscriptionPlan,
  'videoLimit' : bigint,
  'price' : bigint,
  'photoLimit' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StarredEntry {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'imageUrl' : string,
  'userPrincipal' : Principal,
  'prompt' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type SubscriptionPlan = { 'max' : null } |
  { 'pro' : null } |
  { 'growth' : null } |
  { 'starter' : null } |
  { 'basic' : null };
export interface SubscriptionUsage {
  'lastReset' : Time,
  'photosUsed' : bigint,
  'createdAt' : Time,
  'plan' : SubscriptionPlan,
  'videosUsed' : bigint,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCustomTheme' : ActorMethod<[string, string], bigint>,
  'addDesign' : ActorMethod<[string, string], bigint>,
  /**
   * / Add a starred design (returns entry id)
   */
  'addStarredEntry' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimRazorpayPayment' : ActorMethod<[string, SubscriptionPlan], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCustomTheme' : ActorMethod<[bigint], undefined>,
  /**
   * / Deletes a starred design for a user, if it exists
   */
  'deleteStarredEntry' : ActorMethod<[bigint], undefined>,
  /**
   * / Returns the number of AI Generation logs that have been created
   */
  'getAiGenerationLogCount' : ActorMethod<[], bigint>,
  /**
   * / Gets all logs (sorted by oldestId) (admin-only)
   */
  'getAiGenerationLogs' : ActorMethod<[], Array<AiGenerationLog>>,
  /**
   * / Gets all logs in reverse order (admin-only)
   */
  'getAiGenerationLogsReverse' : ActorMethod<[], Array<AiGenerationLog>>,
  /**
   * / Gets all logs (sorted by createdAt desc) (admin-only)
   */
  'getAiGenerationLogsSorted' : ActorMethod<[], Array<AiGenerationLog>>,
  'getAllDesigns' : ActorMethod<[], Array<DesignEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesignHistorySorted' : ActorMethod<[], Array<DesignEntry>>,
  'getImage' : ActorMethod<[ExternalBlob], ExternalBlob>,
  'getMyCustomThemes' : ActorMethod<[], Array<CustomTheme>>,
  'getMyProfile' : ActorMethod<[], UserProfile>,
  /**
   * / Get all of the caller's own starred entries (sorted by createdAt desc)
   */
  'getMyStarredEntries' : ActorMethod<[], Array<StarredEntry>>,
  /**
   * / Returns the number of starred entries for a user.
   */
  'getMyStarredEntryCount' : ActorMethod<[], bigint>,
  'getMySubscription' : ActorMethod<[], SubscriptionUsage>,
  'getPlanLimitsQuery' : ActorMethod<[SubscriptionPlan], PlanLimits>,
  'getPuterToken' : ActorMethod<[], string>,
  /**
   * / Get starred entries for a user (admin-only)
   */
  'getStarredEntries' : ActorMethod<[Principal], Array<StarredEntry>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  /**
   * / Returns the number of starred entries created by all users (admin-only).
   */
  'getTotalStarredEntryCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  /**
   * / Used by backend to store logs
   */
  'logAiGeneration' : ActorMethod<[string, string, string], undefined>,
  'recordPhotoUsage' : ActorMethod<[], undefined>,
  'recordVideoUsage' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'selfRegister' : ActorMethod<[string], undefined>,
  'setPuterToken' : ActorMethod<[string], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserPlan' : ActorMethod<[Principal, SubscriptionPlan], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateMyProfile' : ActorMethod<[string], undefined>,
  /**
   * / Updates the name and description for a starred design (only for the user that created it).
   */
  'updateStarredEntry' : ActorMethod<[bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];