/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SubscriptionPlan = IDL.Variant({
  'max' : IDL.Null,
  'pro' : IDL.Null,
  'growth' : IDL.Null,
  'starter' : IDL.Null,
  'basic' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const DesignEntry = IDL.Record({
  'principal' : IDL.Principal,
  'createdAt' : Time,
  'style' : IDL.Text,
  'roomType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const CustomTheme = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'prompt' : IDL.Text,
});
export const SubscriptionUsage = IDL.Record({
  'lastReset' : Time,
  'photosUsed' : IDL.Nat,
  'createdAt' : Time,
  'plan' : SubscriptionPlan,
  'videosUsed' : IDL.Nat,
});
export const PlanLimits = IDL.Record({
  'plan' : SubscriptionPlan,
  'videoLimit' : IDL.Nat,
  'price' : IDL.Nat,
  'photoLimit' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomTheme' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimRazorpayPayment' : IDL.Func([IDL.Text, SubscriptionPlan], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCustomTheme' : IDL.Func([IDL.Int], [], []),
  'getAllDesigns' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDesignHistorySorted' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
  'getMyCustomThemes' : IDL.Func([], [IDL.Vec(CustomTheme)], ['query']),
  'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
  'getMySubscription' : IDL.Func([], [SubscriptionUsage], ['query']),
  'getPlanLimitsQuery' : IDL.Func([SubscriptionPlan], [PlanLimits], []),
  'getPuterToken' : IDL.Func([], [IDL.Text], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'recordPhotoUsage' : IDL.Func([], [], []),
  'recordVideoUsage' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegister' : IDL.Func([IDL.Text], [], []),
  'setPuterToken' : IDL.Func([IDL.Text], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'setUserPlan' : IDL.Func([IDL.Principal, SubscriptionPlan], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateMyProfile' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SubscriptionPlan = IDL.Variant({
    'max' : IDL.Null,
    'pro' : IDL.Null,
    'growth' : IDL.Null,
    'starter' : IDL.Null,
    'basic' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const DesignEntry = IDL.Record({
    'principal' : IDL.Principal,
    'createdAt' : Time,
    'style' : IDL.Text,
    'roomType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const CustomTheme = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'prompt' : IDL.Text,
  });
  const SubscriptionUsage = IDL.Record({
    'lastReset' : Time,
    'photosUsed' : IDL.Nat,
    'createdAt' : Time,
    'plan' : SubscriptionPlan,
    'videosUsed' : IDL.Nat,
  });
  const PlanLimits = IDL.Record({
    'plan' : SubscriptionPlan,
    'videoLimit' : IDL.Nat,
    'price' : IDL.Nat,
    'photoLimit' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomTheme' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addDesign' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimRazorpayPayment' : IDL.Func([IDL.Text, SubscriptionPlan], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCustomTheme' : IDL.Func([IDL.Int], [], []),
    'getAllDesigns' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDesignHistorySorted' : IDL.Func([], [IDL.Vec(DesignEntry)], ['query']),
    'getMyCustomThemes' : IDL.Func([], [IDL.Vec(CustomTheme)], ['query']),
    'getMyProfile' : IDL.Func([], [UserProfile], ['query']),
    'getMySubscription' : IDL.Func([], [SubscriptionUsage], ['query']),
    'getPlanLimitsQuery' : IDL.Func([SubscriptionPlan], [PlanLimits], []),
    'getPuterToken' : IDL.Func([], [IDL.Text], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'recordPhotoUsage' : IDL.Func([], [], []),
    'recordVideoUsage' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegister' : IDL.Func([IDL.Text], [], []),
    'setPuterToken' : IDL.Func([IDL.Text], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'setUserPlan' : IDL.Func([IDL.Principal, SubscriptionPlan], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateMyProfile' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };